name: vpn_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/Encrypt.png
    - assets/icons/Hide.png
    - assets/icons/Ip.png
    - assets/icons/SecureConversations.png

  fonts:
    - family: Sf Pro Display
      fonts:
        - asset: fonts/sf_pro_display/SF-Pro-Display-Bold.otf
          weight: 700

    - family: Jost
      fonts:
        - asset: fonts/Jost/Jost.ttf
          weight: 400
